let CompuPrendida = true;
console.log(CompuPrendida);
let IrAPlayground = "Entrar a la pagina Playground";
console.log(IrAPlayground);
let InicioDeZoom = "13:30";
console.log(InicioDeZoom);
let Materia = "Programacion Imperativa";
console.log(Materia);
let TengoCafe = true;
console.log(TengoCafe);
let DuracionDeLaClase = 2;
console.log(DuracionDeLaClase + " hs");
let TotalEstudiantes = 60;
console.log(TotalEstudiantes);
let Carrera = "Tech Developing";
console.log(Carrera);
let RelevacionDeDudas = "muchas"; 
console.log(RelevacionDeDudas);
let FinDeLaClase = "15:30"; 
console.log(FinDeLaClase);